---
- name: "ensure systemd path exists"
  file:
    path: "/usr/lib/systemd/system"
    state: directory
    owner: "root"
    group: "root"
    mode: "0760"
- name: "isntall systemd file"
  copy:
    src: "pimd.target"
    dest: "/usr/lib/systemd/system/pimd.target"
    owner: "root"
    group: "root"
    mode: "0640"
- name: "install pimd"
  apt:
    pkg: pimd
    state: installed
- name: "check for pimd config"
  stat:
    path: "/etc/pimd.conf"
  register: pimd_exists
- name: "generate pimd config"
  template:
    src: pimd.conf
    dest: "/etc/pimd.conf"
    owner: root
    group: root
    mode: 0660
  register: pimd_config
- name: "start pimd the first time"
  command: service pimd start
  when: not pimd_exists.stat.exists
- name: "restart pimd"
  command: service pimd restart
  when: pimd_exists.stat.exists and pimd_config.changed
